version: "3"
services:
  proxy:
    image: httpd:alpine 
    ports:
      - "80:80"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
  app:
    build: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
  